package enumtype.firstenum;

public enum Football {
    STRIKER, CENTERFORWARD, WINGERS,
    LEFTMID, RIGHTMID, CENTERMID, ATTACKINGMID, DEFENSIVEMID ,
    CENTERBACK, LEFTBACK, RIGHTBACK, WINGBACKS, SWEEPER,
    GOALKEEPER

}
